# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Multiplicative Update of P
mu_P_cpp <- function(Y, Theta, s, meds, P, beta, wt) {
    .Call('_ARTdeConv_mu_P_cpp', PACKAGE = 'ARTdeConv', Y, Theta, s, meds, P, beta, wt)
}

#' Multiplicative Update of Theta
mu_Theta_cpp <- function(Y, s, P, Theta_0, Delta, Delta_c, Theta, alpha1, alpha2) {
    .Call('_ARTdeConv_mu_Theta_cpp', PACKAGE = 'ARTdeConv', Y, s, P, Theta_0, Delta, Delta_c, Theta, alpha1, alpha2)
}

#' Multiplicative Update of S
mu_s_cpp <- function(Y, Theta, s, P) {
    .Call('_ARTdeConv_mu_s_cpp', PACKAGE = 'ARTdeConv', Y, Theta, s, P)
}

#' Function for getting the Delta matrix
get_Delta_cpp <- function(k, k0, m, m0) {
    .Call('_ARTdeConv_get_Delta_cpp', PACKAGE = 'ARTdeConv', k, k0, m, m0)
}

#' Function for getting the complement of the Delta matrix
get_Delta_c_cpp <- function(Delta) {
    .Call('_ARTdeConv_get_Delta_c_cpp', PACKAGE = 'ARTdeConv', Delta)
}

#' ARTdeConv objective function
obj_fun_cpp <- function(Y, Y_hat, Theta_hat, P_hat, m0, k0, Theta_0, Delta, Delta_c, meds, ranges, alpha_1, alpha_2, beta) {
    .Call('_ARTdeConv_obj_fun_cpp', PACKAGE = 'ARTdeConv', Y, Y_hat, Theta_hat, P_hat, m0, k0, Theta_0, Delta, Delta_c, meds, ranges, alpha_1, alpha_2, beta)
}

#' Core ARTdeConv Function For One Set of Initial Values (in C++)
#'
#' This is the core function that will run ARTdeConv once under a set of initial values. It is written in C++ 
#' and integrated in R through Rcpp and RcppArmadillo. Users running this function should provide their own 
#' initial values in the input. Otherwise, the required parameters are the same as the main ARTdeConv function
#' with restarts.
#'
#' @param Y the bulk matrix.
#' @param Theta_0 the partial reference matrix that we have prior knowledge about. The unknown part of 
#' @param Theta_it the initial value of Theta.
#' @param s_it the initial value of the main diagonal of S.
#' @param P_it the initial value of P.
#' @param m0 the number of gene features we have prior knowledge about in `Theta_0`. 
#' @param k0 the number of cell types whose cell-type level expression we have prior knowledge about in `Theta_0`.
#' @param meds the vector of median cell proportions in the population.
#' @param ranges the vector of the range interval lengths of proportions of different cell types.
#' @param alpha1 the tuning parameter for regularizing the part of Theta with prior knowledge.
#' @param alpha2 the tuning parameter for regularizing the part of Theta without prior knowledge.
#' @param beta the tuning parameter for regularizing P.
#' @param max_iter the maximal number of iterations this core function will run. The default is `1e5`.
#' @param tol the tolerance parameter for the convergence criterion of ARTdeConv. The default is `1e-5`.
artdeconv_single_solve_cpp <- function(Y, Theta_0, Theta_it, s_it, P_it, m0, k0, meds, ranges, alpha1, alpha2, beta, max_iter = 1e5L, tol = 1e-5) {
    .Call('_ARTdeConv_artdeconv_single_solve_cpp', PACKAGE = 'ARTdeConv', Y, Theta_0, Theta_it, s_it, P_it, m0, k0, meds, ranges, alpha1, alpha2, beta, max_iter, tol)
}

#' Core ARTdeConv Function For One Set of Initial Values Assuming a Fixed S (in C++)
#'
#' This is the core function that will run ARTdeConv once under a set of initial values, but with the legacy bi-factor assumption (that the scale matrix S is fixed). 
#' It is written in C++ and integrated in R through Rcpp and RcppArmadillo. It can technically increase the speed since S will not be updated,
#' but should be only used when the user is confident that S can be represented by the identity matrix. Users running this function should provide their own 
#' initial values in the input. Otherwise, the required parameters are the same as the main ARTdeConv function
#' with restarts.
#'
#' @param Y the bulk matrix.
#' @param Theta_0 the partial reference matrix that we have prior knowledge about. The unknown part of 
#' @param Theta_it the initial value of Theta.
#' @param P_it the initial value of P.
#' @param m0 the number of gene features we have prior knowledge about in `Theta_0`. 
#' @param k0 the number of cell types whose cell-type level expression we have prior knowledge about in `Theta_0`.
#' @param meds the vector of median cell proportions in the population.
#' @param ranges the vector of the range interval lengths of proportions of different cell types.
#' @param alpha1 the tuning parameter for regularizing the part of Theta with prior knowledge.
#' @param alpha2 the tuning parameter for regularizing the part of Theta without prior knowledge.
#' @param beta the tuning parameter for regularizing P.
#' @param max_iter the maximal number of iterations this core function will run. The default is `1e5`.
#' @param tol the tolerance parameter for the convergence criterion of ARTdeConv. The default is `1e-5`.
artdeconv_single_solve_s_fixed_cpp <- function(Y, Theta_0, Theta_it, P_it, m0, k0, meds, ranges, alpha1, alpha2, beta, max_iter = 1e5L, tol = 1e-5) {
    .Call('_ARTdeConv_artdeconv_single_solve_s_fixed_cpp', PACKAGE = 'ARTdeConv', Y, Theta_0, Theta_it, P_it, m0, k0, meds, ranges, alpha1, alpha2, beta, max_iter, tol)
}

